# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details
#
# See Also:
# https://readthedocs.org/dashboard/xdoctest/advanced/

# Required
version: 2

build:
  os: "ubuntu-24.04"
  tools:
    python: "3.13"

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/source/conf.py

# Build documentation with MkDocs
#mkdocs:
#  configuration: mkdocs.yml

# Optionally build your docs in additional formats such as PDF and ePub
formats: all

python:
  install:
  - requirements: requirements/docs.txt
  - method: pip
    path: .
      #extra_requirements:
      #  - docs

#conda:
#  environment: environment.yml
